services:
  sf-server:
    #build: .
    image: sineware/securefront:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./tls:/root/.acme.sh
      - ./securefront.config.toml:/app/securefront.config.toml