services:
  sf-server:
    build: .
    #image: sineware/securefront:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/tls:/root/.acme.sh
      - ${PWD}/securefront.config.toml:/app/securefront.config.toml